name: AlcarisCore
version: '1.0.0-somen1000'
main: net.alcaris.plugin.core.AlcarisCore
api-version: '1.21'
authors: [ 'Alcaris Team' ]
description: Core library of all homebrew plugins
website: https://www.alcaris.net
commands:
    alcaris:
      description: "Main command for AlcarisCore"
      usage: /alcaris <subcommand> [args...]